version: '3.8'

services:
  mynginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    user: "www" 